interface=wlan0
driver=nl80211

ssid=lain
hw_mode=g
channel=1
bridge=br0

country_code=ID
ieee80211n=1
ieee80211d=1
ieee80211h=1
ht_capab=[HT20][SHORT-GI-20]
uapsd_advertisement_enabled=0
wmm_enabled=1
max_num_sta=10

auth_algs=1
wpa=2
wpa_passphrase=wereallconnected
wpa_key_mgmt=WPA-PSK
rsn_pairwise=CCMP
