table inet filter {
	chain input {
		type filter hook input priority filter; policy accept;
	}

	chain forward {
		type filter hook forward priority filter; policy accept;
	}

	chain output {
		type filter hook output priority filter; policy accept;
	}
}
table ip nat {
	chain POSTROUTING {
		type nat hook postrouting priority srcnat; policy accept;
		ip saddr 192.168.100.0/24 ip daddr != 192.168.100.0/24 masquerade
	}

	chain PREROUTING {
		type nat hook prerouting priority dstnat; policy accept;
		iifname "br0" udp dport 53 dnat to 192.168.100.1:53
		iifname "br0" tcp dport 53 dnat to 192.168.100.1:53
	}
}
table ip6 nat {
	chain POSTROUTING {
		type nat hook postrouting priority srcnat; policy accept;
		ip6 saddr dead:beef::/64 ip6 daddr != dead:beef::/64 masquerade
	}

	chain PREROUTING {
		type nat hook prerouting priority dstnat; policy accept;
		iifname "br0" udp dport 53 dnat to [dead:beef::1]:53
		iifname "br0" tcp dport 53 dnat to [dead:beef::1]:53
	}
}
table ip mangle {
	chain postrouting {
		type filter hook postrouting priority mangle; policy accept;
		oifname "wwan0" ip ttl set 65
	}
}
table ip6 mangle {
	chain postrouting {
		type filter hook postrouting priority mangle; policy accept;
		oifname "wwan0" ip6 hoplimit set 65
	}
}
